### ISSUE TITLE
Delete/Report listing button

### ISSUE THREAD

**Issue by joycesin** [limyifan1/hawkercentral#11]
Similar functionality to #8 

We would like to add a delete button next to the edit button with the same functionality as PR #8 which sends an email message to foodleh@outlook.com titled "Please delete listing.." with some listing identifier.

**Comment by joanneong** [comment]
Hi, I'm looking into this now. Is delete considered to be the same as report in this case?

**Comment by limyifan1** [comment]
We were thinking that we can be notified via email/notification if someone reports it :) pretty similar to what you implemented for the edit button!
