### ISSUE TITLE
Code refactoring for Components usage and constant values like cuisines

### ISSUE THREAD

**Issue by mervintankw** [limyifan1/hawkercentral#15]
Would suggest refactoring SearchAll and Nearby components to be a single common component. That will make it easier to maintain over time. As well as abstracting cuisines values into a common file for easier access and maintainability.

**Comment by limyifan1** [comment]
Agree! We did that for the Create page and Edit Popup which has worked well. We will work to build a component for SearchAll and Nearby as you suggested too :)

**Comment by LoneRifle** [comment]
Fixed in #115 so issue can be closed

**Comment by joycesin** [comment]
thank you!
