### ISSUE TITLE
Querying: drop client-side filtering in favour of server-side equivalent

### ISSUE THREAD

**Issue by LoneRifle** [limyifan1/hawkercentral#16]
I thought to drop a question here for @limyifan1 - browsing through the commit log, I've noticed that you moved from performing the search using Google Cloud Functions to retrieving entries directly from Firebase and filtering client-side. 

Given that you are familiar with the data schema, would making a Firebase query be viable? If so, I'm willing to submit a PR that would move some of the filtering criteria into query clauses.

**Comment by LoneRifle** [comment]
Inspection of the data model suggests its current form may not be suited for such queries.

**Comment by limyifan1** [comment]
Hi LoneRifle, thanks for the feedback :) The reason why I moved search away from Cloud Functions was that loading was really slow and I wasn't sure why. If you are able to help with that I am all ears! I suspect it is because using Cloud Function made it a two-step "query".
