### ISSUE TITLE
Minor UI Bug: Claps

### ISSUE THREAD

**Issue by joycesin** [limyifan1/hawkercentral#17]
When a listing has more than 3-digit claps, it exceeds the space in the clap sticker on the thumbnail, and the clap image is cut off, which looks weird. Fix is probably to make the clap sticker size dynamically above 3 digits, other suggestions welcome too. Making font size smaller is possible but might look wonky. Picture attached for clarity, 4 digit vs 2 digit.

<img width="214" alt="Screen Shot 2020-04-26 at 4 40 31 AM" src="https://user-images.githubusercontent.com/26424769/80290531-2a13fe00-8778-11ea-8944-306bf241e900.png">

<img width="215" alt="Screen Shot 2020-04-26 at 4 45 17 AM" src="https://user-images.githubusercontent.com/26424769/80290597-da820200-8778-11ea-8e36-bf2473d5a9b4.png">

**Comment by nataliepina** [comment]
Hi! I'd like to help with this issue.

**Comment by limyifan1** [comment]
@nataliepina Thanks for the offer to help :) I believe @mervintankw had helped to fix the bug!
