### ISSUE TITLE
Let users open individual listings in a new window

### ISSUE THREAD

**Issue by alanwuha** [limyifan1/hawkercentral#171]
Current listings won't let you open in a new window, weird for users who usually want to see many at once.

Awesome project! Would love to contribute to this project if it is still ongoing.

Questions:
- do we mean to open a new tab (instead of window) on click of an item?
- should the current tab be switched to the newly opened tab or stay on the listings tab?

**Comment by limyifan1** [comment]
Hi Alan, thanks for checking us out :) this is a good idea to implement! We're still running although with occasional development changes. 

To answer your questions: 
1. Opening a new tab should make more sense as it'll be less disruptive! 
2. Hmm is this a browser-reliant interaction? Always assumed when you click "Open in New Tab" whether it stays in the current window depends on the browser. If we get to choose, I would go with staying on the listings tab. 

Feel free to let us know if you have further questions :)

**Comment by alanwuha** [comment]
Oh hey @limyifan1  thanks for the quick reply!

Response to `2`: Was thinking of using the `window.open()` method but this switches to the new tab. I'll see if there's a way to open a new tab while staying on the listings tab.

Actually this is an item listed in `contributing.md` under 'General Task (No. 4)'. Just to clarify, it's asking for the __left click__ to open a new tab right? Cause technically opening links in new tabs can be done using right click + "Open link in New Tab" or clicking the item using the mouse scroll...

**Comment by limyifan1** [comment]
Ah I see! Actually I believe we were thinking of a right click, which was added previously. We had pages redirect with onClick instead of link clicks. If that’s the case letting users left click to open a new window was not what we had in mind. Is this something you think will help? Will be happy to look into adding it :)

**Comment by alanwuha** [comment]
Oh okay, then I guess the status quo should be fine! Users currently have the option of opening the link in a new tab or window using right click. I'll just close this issue, thanks for the clarification.

Would love to help out with other issues in future, do give a shout out!

**Comment by alanwuha** [comment]
Oh and opening a new background tab using the left click seems to break away from the intuitive and conventional browser behavior so probably not a good function.

I think opening a new tab and switching to the new tab using the left click is the intuitive norm, but this probably makes it more disruptive in this case. Haha. So yeah status quo is good!
