### ISSUE TITLE
Slow keyword search

### ISSUE THREAD

**Issue by joycesin** [limyifan1/hawkercentral#18]
Open-ended question - noticed that website takes longer to load search results as more listings come up. Suggestions welcome!

Possible reasons:
- Currently updating search results every time a character is added, should it only be updated when user hits Enter?
- Some server-side issue that we're not aware of?

**Comment by mervintankw** [comment]
@joycesin you can consider adding like a 100-300ms delay before trying to process a user's search entry, that way the app will not immediately start searching as the user is still typing, which results in rather choppy experience.

**Comment by limyifan1** [comment]
okay! I was trying to implement something like this: https://stackoverflow.com/questions/42217121/searching-in-react-when-user-stops-typing
So i changed my handleChange function to become: 

  handleChange = (event) => {
    const target = event.target;
    const value = target.value;
    const name = target.name;
    if (this.state.typingTimeout) {
      clearTimeout(this.state.typingTimeout);
    }

    this.setState({
      [name]: value,
      typing: false,
      typingTimeout: setTimeout(function () {
        this.sendToParent(this.state[name]);
      }, 5000),
    });
  };

Still didn't seem to work... any idea?

**Comment by mervintankw** [comment]
I think you can initialise a global variable within the component like this

`
let searchTimer = null;

export class YourComponent extends React.Component {

	handleChange = (event) => {
		const self = this;
		const target = event.target;
		const value = target.value;
		const name = target.name;
		clearTimeout(searchTimer);
		searchTimer = setTimeout(() => {
			self.setState({ [name]: value });
		}, 5000);
	}

}
`

The above will set state only after 5 seconds, but if the user keeps typing, then the timer will constant reset every time handleChange function is called. Hope this helps!

**Comment by limyifan1** [comment]
This is perfect, it works now. So so grateful for your constant contributions :)

**Comment by wentjun** [comment]
I am not a fan of the above approach of using settimeout to handle debouncing of input.

1) It is not recommended to use mutable variables such as `let` for a value that is deemed to be a constant value.

2) In the long run, it would be more sustainable to handle this via using RxJS through the usage of `debounceTime`.

3) Part of the above code can be simplified as 

`const { target: { value, name } } = event;`

**Comment by limyifan1** [comment]
Thanks for the suggestion! I've pushed suggestion #3. For #1, react doesn't seem to let me use const, perhaps there's another way! Also for #2 We'll dig deeper and keep that in mind :)
