### ISSUE TITLE
Adopt and enforce DCO

### ISSUE THREAD

**Issue by achrinza** [limyifan1/hawkercentral#20]
## What is the issue?

Currently, any users can contribute to the project without signing a CLA or DCO. This could potentially leave the repository at risk of liability should a contributor include code or other materials that infringes existing copyright.

A DCO is recommended over a CLA as it is more "relaxed" and therefore has a lower barrier of entry for contributions.

The most common DCO used is [the one provided by The Linux Foundation](https://developercertificate.org/):

<details>
<summary>DCO text</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

## How to rectify this issue?

DCOs are enforced by requiring a signoff in every commit using `git commit --signoff` (or `git commit -s`) and by a CI pipeline or a [bot](https://probot.github.io/apps/dco/).

**A signoff does not automatically equate to an agreement to a DCO**. Hence, it is important to document the DCO in a `CONTRIBUTING.md` file and/or in a PR template so as to make it clear to the contributor the purpose of the signoff.

The documentation of the signoff purpose can be written as follows:

> To acknowledge the Developer Certificate of Origin (DCO), sign your commits by adding Signed-off-by: John Doe <john.doe@email.com> to the last line of each Git commit message. The e-mail address used to sign must match the e-mail address of the Git author.

**Comment by joycesin** [comment]
thanks for sharing this issue! added DCO info to CONTRIBUTING.md 👍

**Comment by achrinza** [comment]
The DCO bot doesn't seem to be configured yet, we should add it so that the DCO can be enforced via a PR status check.
