### ISSUE TITLE
Use a dependency auto updater

### ISSUE THREAD

**Issue by achrinza** [limyifan1/hawkercentral#21]
## What's the issue?

Currently there's no "dependency auto updater". Due to the nature of the Node.js ecosystem, this could cause dependencies and the package locks to go stale relatively quickly and potentially leave certain dependency vulnerabilities unchecked.

## How to rectify the issue?

[WhiteSource Rennovate](https://github.com/marketplace/renovate) is free, popular GitHub bot for automatically creating PRs to update dependencies and package locks.

**Comment by limyifan1** [comment]
Great tool :) Successfully installed!
