### ISSUE TITLE
Slow loading and high network usage

### ISSUE THREAD

**Issue by joycesin** [limyifan1/hawkercentral#23]
**Credits for noticing & possible solutions to a fellow dev who messaged us on FB. Thank you!**

Issue: We are currently loading full-sized images for thumbnail icons, possible solutions:

- Make multiple sizes of each image on Firebase, load right image size based on device viewport
- Endpoint/microservice that processes the image based on the viewport
- Use webp image format instead of jpg/png for better compression

**Comment by kohchihao** [comment]
Hello, I saw you all were using Firebase. Firebase has this `Firebase Extension` where you can resize images stored in Firebase. Can consider trying https://firebase.google.com/products/extensions/storage-resize-images

**Comment by limyifan1** [comment]
Perfect, I looked at the documentation and realized I've been on the right track. I've used JIMP to decrease the image quality but not the image size. Fixed now!

**Comment by limyifan1** [comment]
Now the issue: how do we resize those that are already in our Firebase Cloud Storage?

**Comment by limyifan1** [comment]
Managed to compress all cover images. Greatly improved performance but got to look into converting into webp.
