### ISSUE TITLE
Remove references to The Smart Local

### ISSUE THREAD

**Issue by achrinza** [limyifan1/hawkercentral#27]
See:

- https://github.com/limyifan1/hawkercentral/blob/1494a29efb17c58333246b8aaf5f72a52f1bdf0e/src/Components/data.html
- https://github.com/limyifan1/hawkercentral/blob/1494a29efb17c58333246b8aaf5f72a52f1bdf0e/src/Components/out.csv
- https://github.com/limyifan1/hawkercentral/blob/1494a29efb17c58333246b8aaf5f72a52f1bdf0e/src/Components/SearchAll.js#L306
- https://github.com/limyifan1/hawkercentral/blob/1494a29efb17c58333246b8aaf5f72a52f1bdf0e/src/Components/addData.js#L201
- https://github.com/limyifan1/hawkercentral/blob/1494a29efb17c58333246b8aaf5f72a52f1bdf0e/src/Components/Nearby.js#L337

**Comment by limyifan1** [comment]
Done! Thanks for the good catch...
