### ISSUE TITLE
What to contribute to?

### ISSUE THREAD

**Issue by jacobtyq** [limyifan1/hawkercentral#29]
Hi, I'm not too sure where or what to start contributing to. 

I forked the repository and will probably look into 
- Folder Organisation (Assets or Components)
- Possible Refactor (I haven't taken a look at the codebase yet but saw a suggestion on (https://github.com/limyifan1/hawkercentral/issues/15) about it
- Performance, Not too sure how much I can contribute to this (https://github.com/limyifan1/hawkercentral/issues/23)

Let me know if there is a roadmap or somewhere a feature or chore that needs prioritizing :)

**Comment by limyifan1** [comment]
Hi jacobtyq :) We are in fact working on a product roadmap, will upload it as soon we are done! Right now actually we're working to see if we can get a way to have a moderator system for edits... will post an issue on that.

**Comment by limyifan1** [comment]
Oh we actually have that under #8 . Will start looking at that soon!

**Comment by joycesin** [comment]
thanks for hopping in to help! hope things are a bit more organised, made a CONTRIBUTING.md as per issue #32 

https://github.com/limyifan1/hawkercentral/blob/master/CONTRIBUTING.md
