### ISSUE TITLE
Adding listeners for cookies

### ISSUE THREAD

**Issue by joycesin** [limyifan1/hawkercentral#49]
Issue: [Translation branch] Other components eg in Home.js, etc need to know when the language cookie is set in Menu.js

Currently using universal-cookie: https://www.npmjs.com/package/universal-cookie and there is an addChangeListener function. However, I can't seem to get it working, this code snippet in Home.js simply doesn't trigger an update when I set the cookie in Menu.js. 

```
const cookies = new Cookies();

cookies.addChangeListener(onCookieChange);

function onCookieChange() {
  console.log("Noticed cookie change!")
}
```

Tried binding onCookieChange like this:
`cookies.addChangeListener(this.onCookieChange.bind(this));`
and got this error:
`TypeError: Cannot read property 'onCookieChange' of undefined`

**Comment by bolstycjw** [comment]
Looking at the source, it appears that the changeListener applies to the cookie instance itself. You would need to pass in the same cookie instance for all your pages for it to work.
https://github.com/reactivestack/cookies/blob/bb68224696a59d8089fa85aa4f116c205ff31a92/packages/universal-cookie/src/Cookies.ts#L101

**Comment by joycesin** [comment]
hmm okay, thanks for pointing this out! Thinking that the best way around this is to use React Context now, any other possible solutions? https://reactjs.org/docs/context.html

**Comment by bolstycjw** [comment]
yes, i would also suggest storing the language state in context instead and have the cookie be read and changed at the app root with useReducer.

**Comment by joycesin** [comment]
got it working! Thank you :)
