### ISSUE TITLE
Returning to same position on page after viewing listing 

### ISSUE THREAD

**Issue by limyifan1** [limyifan1/hawkercentral#52]
We want users to be able to return to same position in the page instead of starting at the top when they click on a listing. Will greatly improve user experience.

**Comment by joanneong** [comment]
@limyifan1 Can I clarify what are the ways in which a user can return to all listings after they view a particular listing? Right now, it seems like the only way is to press on the "Go back one page" arrow in the browser:

<img width="901" alt="image" src="https://user-images.githubusercontent.com/24493463/80914318-71ece380-8d7d-11ea-857b-a7f22be9be6b.png">

**Comment by joycesin** [comment]
Yup it's just that arrow!

**Comment by joycesin** [comment]
fixed!
