### ISSUE TITLE
Order Management System

### ISSUE THREAD

**Issue by joycesin** [limyifan1/hawkercentral#64]
Issue: We would like customers to be able to create an order, view total price, and send the complete order with address details and contact info via WhatsApp to the hawker.

1. Need to reformat menu item entry to be a dynamic array instead of current 10 entry fields
2. Need to incorporate Take.sg data (which they've kindly shared with us!)
3. Need to add logic to select # items, calculate price, send custom WhatsApp message.

**Comment by LoneRifle** [comment]
Consider replacing this issue with a GitHub Project, and creating more detailed issues within that project. This would allow others to take on the issues more easily

**Comment by joycesin** [comment]
That's a really good suggestion, didn't know about GitHub Projects before this but it does look like a better idea for a larger feature like this. We've implemented this one for now but will definitely do this in future for similar features! Thanks :)
