### ISSUE TITLE
Enforce DCO

### ISSUE THREAD

**Issue by achrinza** [limyifan1/hawkercentral#78]
Quoting from https://github.com/limyifan1/hawkercentral/issues/20#issuecomment-621515041:

> The DCO bot doesn't seem to be configured yet, we should add it so that the DCO can be enforced via a PR status check.

Let's [enable the bot](https://probot.github.io/apps/dco/) and make it a [required status check](https://help.github.com/en/github/administering-a-repository/about-required-status-checks). Otherwise, #20 is not effective and may become a liability.

**Comment by limyifan1** [comment]
Enabled and added rule!

**Comment by LoneRifle** [comment]
The rule is incorrect - you have enabled the rule that requires contributors to sign their commits [with their cryptographic key](https://help.github.com/en/github/authenticating-to-github/about-commit-signature-verification). This is different from the kind of signoffs that the DCO bot is looking for (as is demonstrated by the DCO check passing while merging still being prevented

**Comment by limyifan1** [comment]
Hi thanks for the heads-up! Is this right now? Haha not familiar with these rules so might be doing it wrong again
<img width="726" alt="Screen Shot 2020-05-11 at 6 47 54 PM" src="https://user-images.githubusercontent.com/35542285/81553606-fb249b80-93b7-11ea-9788-8f34015ddfc5.png">

**Comment by LoneRifle** [comment]
Yea that looks right. Thanks for looking into this!
