### ISSUE TITLE
Enforce passing status checks

### ISSUE THREAD

**Issue by achrinza** [limyifan1/hawkercentral#79]
Currently, the PRs do not enforce passing status checks from the CI pipeline. This makes the status checks ineffective. Hence, let's make them [required status checks](https://help.github.com/en/github/administering-a-repository/about-required-status-checks).

**Comment by limyifan1** [comment]
Thanks for checking in on us and making sure we're well covered :) I got this following error while trying to add a rule, wonder if you know if there's something else I need to configure first?
<img width="1106" alt="Screen Shot 2020-05-10 at 8 13 06 AM" src="https://user-images.githubusercontent.com/35542285/81488004-2616ce80-9296-11ea-99cf-88039c8c96fa.png">

**Comment by limyifan1** [comment]
Oh sorry found out the reason, that was dumb
