### ISSUE TITLE
Changing free edit access

### ISSUE THREAD

**Issue by joycesin** [limyifan1/hawkercentral#8]
We wanted all users to be able to edit listings so we gave free edit access, but realise that this makes our site vulnerable to misuse by bad people. So the next step is to change the edit button on each listing to trigger an email request to foodleh@outlook.com where we will manually review edit requests.

**Comment by joanneong** [comment]
Hi, I started looking into this and I have a quick question: how would the team like the user to be notified that their edits are undergoing review? Would the team prefer an additional div to appear in the listing page:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/24493463/81461303-71b97180-91dd-11ea-8f25-e7c27baca158.png">

Or another popup to replace the edit pop-up?

<img width="960" alt="image" src="https://user-images.githubusercontent.com/24493463/81461422-3a979000-91de-11ea-99be-9001a960b0d9.png">

What about the message to show to users? 

Personally, I think having the additional division in the listing page looks better, but I'm not sure if the team might think differently. Feel free to let me know your preferences/whether I'm at liberty to decide these myself!
